image: alpine/latest
packages:
  - uv
  - gcc
  - python3-dev
  - cairo-dev
  - chafa

secrets:
  - b88a4c2c-944c-42a6-9fbb-7483049c458a

sources:
  - git@git.sr.ht:~sfermigier/prezo

tasks:
  - install: |
      cd prezo
      uv sync
  - test: |
      cd prezo
      uv run pytest -q --tb=short
  - lint: |
      cd prezo
      uv run ruff check
      uv run mypy src
  - nox: |
      cd prezo
      uvx nox

triggers:
  - action: email
    condition: failure
    to: sf@fermigier.com
