image: alpine/latest
packages:
  - uv
  - gcc
  - python3-dev
  - cairo-dev
  - chafa

tasks:
  - install: |
      cd prezo
      uv sync
  - test: |
      cd prezo
      uv run pytest -q --tb=short
  - lint: |
      cd prezo
      uv run ruff check
      uv run ty check src
  - nox: |
      cd prezo
      uvx nox

triggers:
  - action: email
    condition: failure
    to: sf@fermigier.com
